In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/krishnag02/Learning Phase/Jupyterfiles/Fortune_500.csv', encoding='latin-1')
df.head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"


In [3]:
data = df.to_numpy()

In [4]:
data

array([[1, 'Walmart', '23,00,000', ..., '-7.2%', '$1,98,825',
        '$2,18,619'],
       [2, 'Berkshire Hathaway', '3,67,700', ..., '0.0%', '$6,20,854',
        '$4,11,035'],
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       ...,
       [498, 'Yahoo', '8,500', ..., '-', '$48,083', '$44,391'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968'],
       [500, 'ABM Industries', '1,10,000', ..., '-25.0%', '$2,281',
        '$2,428']], shape=(500, 10), dtype=object)

#Level 1 — Basics


1. Load the CSV using Pandas and convert it into a NumPy array.
2. Print
  * shape
  * ndim
  * size
  * dtype
3. Print only the first 10 companies.
4. Print the last 15 companies.
5. Extract only the "Company Name" column using NumPy indexing.
6. Extract only the "Rank" column.
7. Print companies ranked from 50 to 100.
8. Print every 5th company.
9. Reverse the dataset using NumPy slicing.
10. Find the unique data types present in the NumPy array.

In [5]:
data.shape

(500, 10)

In [6]:
data.size

5000

In [7]:
data.ndim

2

In [8]:
data.dtype

dtype('O')

In [9]:
data[:10]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004', '-16.7%',
        '$7,840.0', '-51.5%', '$3,30,314', '$3,40,056'],
       [5, 'McKesson', '68,000', 5.0, '$1,92,487', '6.2%', '$2,258.0',
        '53.0%', '$56,563', '$31,439'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
        '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
       [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526', '15.8%',
        '$5,317.0', '1.5%', '$94,462', '$81,310'],
       [8, 'General Motors', '2,25,000', 8.0, '$1,66,380', '9.2%',
        '$9,427.0', '-2.7%', '$2,21,690', '$52,968'],
       [9, 'AT&T', '2,68,540', 10.0, '$1,6

In [10]:
print(data[-15:])

[[486 'Seaboard' '11,781' 460.0 '$5,379' '-3.8%' '$312.0' '82.5%'
  '$4,755' '$4,881']
 [487 'Essendant' '6,600' 477.0 '$5,369' '0.1%' '$63.9' '-' '$2,164'
  '$568']
 [488 'Apache' '3,727' 388.0 '$5,354' '-19.5%' '-$1,405.0' '-' '$22,519'
  '$19,547']
 [489 'Airgas' '17,000' 484.0 '$5,314' '0.2%' '$337.5' '-8.3%' '$6,135'
  '-']
 [490 'Kelly Services' '7,500' 467.0 '$5,277' '-4.4%' '$120.8' '124.5%'
  '$2,028' '$836']
 [491 'Liberty Media' '3,626' 525.0 '$5,276' '10.0%' '$680.0' '962.5%'
  '$31,377' '$13,055']
 [492 'Rockwell Collins' '19,000' 490.0 '$5,259' '-0.1%' '$728.0' '6.1%'
  '$7,707' '$12,711']
 [493 'Robert Half International' '16,400' 503.0 '$5,250' '3.1%' '$343.4'
  '-4.0%' '$1,778' '$6,240']
 [494 'CH2M Hill' '20,000' 478.0 '$5,236' '-2.3%' '$15.0' '-81.3%'
  '$2,671' '-']
 [495 'Big Lots' '23,150' 495.0 '$5,200' '0.2%' '$152.8' '7.0%' '$1,608'
  '$2,180']
 [496 'Michaels Cos.' '31,000' 517.0 '$5,197' '5.8%' '$378.2' '4.2%'
  '$2,148' '$4,229']
 [497 'Toll Brothers' '4,200

In [11]:
data[:,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.', 'United Technologies', 'Marathon Petroleum',
       'Disney', 'Humana', 'Pfizer', 'AIG', 'Lockheed Martin', 'Sysco',
       'FedEx', 'Hewlett Packard Ente

In [12]:
data[:,0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 

In [13]:
data[50:101]

array([[51, 'Marathon Petroleum', '44,460', 42.0, '$55,858', '-13.5%',
        '$1,174.0', '-58.8%', '$44,413', '$26,679'],
       [52, 'Disney', '1,95,000', 53.0, '$55,632', '6.0%', '$9,391.0',
        '12.0%', '$92,033', '$1,79,298'],
       [53, 'Humana', '51,600', 52.0, '$54,379', '0.2%', '$614.0',
        '-51.9%', '$25,396', '$29,743'],
       [54, 'Pfizer', '96,500', 55.0, '$52,824', '8.1%', '$7,215.0',
        '3.7%', '$1,71,615', '$2,03,725'],
       [55, 'AIG', '56,400', 49.0, '$52,367', '-10.2%', '-$849.0',
        '-138.7%', '$4,98,264', '$61,154'],
       [56, 'Lockheed Martin', '97,000', 60.0, '$50,658', '9.8%',
        '$5,302.0', '47.1%', '$47,806', '$77,557'],
       [57, 'Sysco', '51,900', 57.0, '$50,367', '3.5%', '$949.6',
        '38.3%', '$16,722', '$28,048'],
       [58, 'FedEx', '3,35,767', 58.0, '$50,365', '6.1%', '$1,820.0',
        '73.3%', '$46,064', '$52,178'],
       [59, 'Hewlett Packard Enterprise', '1,95,000', nan, '$50,123',
        '-', '$3,161.0', '-'

In [14]:
data[::5]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
        '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
       [11, 'AmerisourceBergen', '18,500', 12.0, '$1,46,850', '8.0%',
        '$1,427.9', '-', '$33,656', '$19,229'],
       [16, 'Costco', '1,72,000', 15.0, '$1,18,719', '2.2%', '$2,350.0',
        '-1.1%', '$33,163', '$73,606'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [26, 'Bank of America Corp.', '2,08,024', 26.0, '$93,662', '0.7%',
        '$17,906.0', '12.7%', '$21,87,702', '$2,36,182'],
       [31, 'Comcast', '1,59,000', 37.0, '$80,403', '7.9%', '$8,695.0',
        '6.5%', '$1,80,500', '$1,78,258'],
       [36, 'Procter & Gamble', '1,05,000', 34.0, '$71,726', '-8.9%',
        '$10,508.0', '49.3%', '$1,27,136', '$2,29,700'],
       [41, 'Dell Te

In [15]:
data[::-1]

array([[500, 'ABM Industries', '1,10,000', ..., '-25.0%', '$2,281',
        '$2,428'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968'],
       [498, 'Yahoo', '8,500', ..., '-', '$48,083', '$44,391'],
       ...,
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [2, 'Berkshire Hathaway', '3,67,700', ..., '0.0%', '$6,20,854',
        '$4,11,035'],
       [1, 'Walmart', '23,00,000', ..., '-7.2%', '$1,98,825',
        '$2,18,619']], shape=(500, 10), dtype=object)

In [16]:
data.flatten()

array([1, 'Walmart', '23,00,000', ..., '-25.0%', '$2,281', '$2,428'],
      shape=(5000,), dtype=object)

In [17]:
set(type(x) for x in data.flatten())

{float, int, str}

#Level 2 — Indexing & Slicing

11. Extract only these columns:
  * Rank
  * Company Name
  * Revenues
12. Extract rows 100–150.
13. Print the first 20 rows and first 5 columns.
14. Print the last 20 rows and last 4 columns.
15. Select companies whose rank is less than 20.
16. Select companies whose rank is between 100 and 150.
17. Print every alternate company.
18. Print every 10th company.
19. Extract the top 50 companies.
20. Extract the bottom 50 companies.

In [18]:
index = [0,1,4]
data[:,index]

array([[1, 'Walmart', '$4,85,873'],
       [2, 'Berkshire Hathaway', '$2,23,604'],
       [3, 'Apple', '$2,15,639'],
       ...,
       [498, 'Yahoo', '$5,169'],
       [499, 'Vistra Energy', '$5,164'],
       [500, 'ABM Industries', '$5,145']], shape=(500, 3), dtype=object)

In [19]:
data[99:150]

array([[100, 'Capital One Financial', '47,300', 112.0, '$27,519', '9.6%',
        '$3,751.0', '-7.4%', '$3,57,033', '$41,831'],
       [101, 'Twenty-First Century Fox', '21,500', 96.0, '$27,326',
        '-5.7%', '$2,755.0', '-66.8%', '$48,365', '$59,949'],
       [102, 'USAA', '29,943', 114.0, '$27,131', '11.4%', '$1,779.1',
        '-21.7%', '$1,47,290', '-'],
       [103, 'World Fuel Services', '5,000', 92.0, '$27,016', '-11.1%',
        '$126.5', '-27.5%', '$5,413', '$2,535'],
       [104, 'Philip Morris International', '79,500', 106.0, '$26,685',
        '-0.4%', '$6,967.0', '1.4%', '$36,851', '$1,75,349'],
       [105, 'Deere', '56,767', 97.0, '$26,644', '-7.7%', '$1,523.9',
        '-21.4%', '$57,981', '$34,648'],
       [106, 'Kraft Heinz', '41,000', 153.0, '$26,487', '44.4%',
        '$3,632.0', '472.9%', '$1,20,480', '$1,10,528'],
       [107, 'Tech Data', '9,500', 108.0, '$26,235', '-0.5%', '$195.1',
        '-26.6%', '$7,932', '$3,569'],
       [108, 'Avnet', '17,700', 102.

In [20]:
data[:20,:5]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639'],
       [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004'],
       [5, 'McKesson', '68,000', 5.0, '$1,92,487'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840'],
       [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526'],
       [8, 'General Motors', '2,25,000', 8.0, '$1,66,380'],
       [9, 'AT&T', '2,68,540', 10.0, '$1,63,786'],
       [10, 'Ford Motor', '2,01,000', 9.0, '$1,51,800'],
       [11, 'AmerisourceBergen', '18,500', 12.0, '$1,46,850'],
       [12, 'Amazon.com', '3,41,400', 18.0, '$1,35,987'],
       [13, 'General Electric', '2,95,000', 11.0, '$1,26,661'],
       [14, 'Verizon', '1,60,900', 13.0, '$1,25,980'],
       [15, 'Cardinal Health', '37,300', 21.0, '$1,21,546'],
       [16, 'Costco', '1,72,000', 15.0, '$1,18,719'],
       [17, 'Walgreens Boots Alliance', '3,00,000', 19.0, '$1,17,351'],
       [1

In [21]:
data[-20:,-4:]

array([['$294.1', '26.5%', '$3,010', '$5,307'],
       ['$7.0', '-', '$6,060', '$7,080'],
       ['$241.2', '-47.2%', '$43,831', '-'],
       ['$900.0', '196.1%', '$8,357', '$12,643'],
       ['-$383.5', '-', '$11,770', '$1,038'],
       ['$312.0', '82.5%', '$4,755', '$4,881'],
       ['$63.9', '-', '$2,164', '$568'],
       ['-$1,405.0', '-', '$22,519', '$19,547'],
       ['$337.5', '-8.3%', '$6,135', '-'],
       ['$120.8', '124.5%', '$2,028', '$836'],
       ['$680.0', '962.5%', '$31,377', '$13,055'],
       ['$728.0', '6.1%', '$7,707', '$12,711'],
       ['$343.4', '-4.0%', '$1,778', '$6,240'],
       ['$15.0', '-81.3%', '$2,671', '-'],
       ['$152.8', '7.0%', '$1,608', '$2,180'],
       ['$378.2', '4.2%', '$2,148', '$4,229'],
       ['$382.1', '5.2%', '$9,737', '$5,872'],
       ['-$214.3', '-', '$48,083', '$44,391'],
       ['-', '-', '$15,167', '$6,968'],
       ['$57.2', '-25.0%', '$2,281', '$2,428']], dtype=object)

In [22]:
result = data[:,0] < 20
data[result]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004', '-16.7%',
        '$7,840.0', '-51.5%', '$3,30,314', '$3,40,056'],
       [5, 'McKesson', '68,000', 5.0, '$1,92,487', '6.2%', '$2,258.0',
        '53.0%', '$56,563', '$31,439'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
        '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
       [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526', '15.8%',
        '$5,317.0', '1.5%', '$94,462', '$81,310'],
       [8, 'General Motors', '2,25,000', 8.0, '$1,66,380', '9.2%',
        '$9,427.0', '-2.7%', '$2,21,690', '$52,968'],
       [9, 'AT&T', '2,68,540', 10.0, '$1,6

In [23]:
result = (data[:,0]>= 100) & (data[:,0] <=150)
data[result]

array([[100, 'Capital One Financial', '47,300', 112.0, '$27,519', '9.6%',
        '$3,751.0', '-7.4%', '$3,57,033', '$41,831'],
       [101, 'Twenty-First Century Fox', '21,500', 96.0, '$27,326',
        '-5.7%', '$2,755.0', '-66.8%', '$48,365', '$59,949'],
       [102, 'USAA', '29,943', 114.0, '$27,131', '11.4%', '$1,779.1',
        '-21.7%', '$1,47,290', '-'],
       [103, 'World Fuel Services', '5,000', 92.0, '$27,016', '-11.1%',
        '$126.5', '-27.5%', '$5,413', '$2,535'],
       [104, 'Philip Morris International', '79,500', 106.0, '$26,685',
        '-0.4%', '$6,967.0', '1.4%', '$36,851', '$1,75,349'],
       [105, 'Deere', '56,767', 97.0, '$26,644', '-7.7%', '$1,523.9',
        '-21.4%', '$57,981', '$34,648'],
       [106, 'Kraft Heinz', '41,000', 153.0, '$26,487', '44.4%',
        '$3,632.0', '472.9%', '$1,20,480', '$1,10,528'],
       [107, 'Tech Data', '9,500', 108.0, '$26,235', '-0.5%', '$195.1',
        '-26.6%', '$7,932', '$3,569'],
       [108, 'Avnet', '17,700', 102.

In [24]:
data[::2]

array([[1, 'Walmart', '23,00,000', ..., '-7.2%', '$1,98,825',
        '$2,18,619'],
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [5, 'McKesson', '68,000', ..., '53.0%', '$56,563', '$31,439'],
       ...,
       [495, 'Big Lots', '23,150', ..., '7.0%', '$1,608', '$2,180'],
       [497, 'Toll Brothers', '4,200', ..., '5.2%', '$9,737', '$5,872'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968']],
      shape=(250, 10), dtype=object)

In [25]:
data[::10]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [11, 'AmerisourceBergen', '18,500', 12.0, '$1,46,850', '8.0%',
        '$1,427.9', '-', '$33,656', '$19,229'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [31, 'Comcast', '1,59,000', 37.0, '$80,403', '7.9%', '$8,695.0',
        '6.5%', '$1,80,500', '$1,78,258'],
       [41, 'Dell Technologies', '1,38,000', nan, '$64,806', '18.1%',
        '-$1,672.0', '-', '$1,18,206', '-'],
       [51, 'Marathon Petroleum', '44,460', 42.0, '$55,858', '-13.5%',
        '$1,174.0', '-58.8%', '$44,413', '$26,679'],
       [61, 'HP', '49,000', 20.0, '$48,238', '-53.3%', '$2,496.0',
        '-45.2%', '$29,010', '$30,231'],
       [71, 'Delta Air Lines', '83,756', 68.0, '$39,639', '-2.6%',
        '$4,373.0', '-3.4%', '$51,261', '$33,586'],
       [81, 'Oracle', '1,36,000', 77.0, '$37,047', '-3

In [26]:
data[:50,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.', 'United Technologies'], dtype=object)

In [27]:
data[-50:,1]

array(['Citizens Financial Group', 'United Rentals', 'Clorox',
       'Genesis Healthcare', 'M&T Bank Corp.', 'Ingredion', 'UGI',
       'Owens Corning', 'S&P Global', 'Markel', 'Wyndham Worldwide',
       'Arthur J. Gallagher', 'Burlington Stores',
       'First American Financial', 'Symantec', 'Patterson', 'Olin',
       'NetApp', 'Raymond James Financial', 'TravelCenters of America',
       'Fiserv', 'Host Hotels & Resorts', 'Insight Enterprises', 'Mattel',
       'AmTrust Financial Services', 'Cincinnati Financial',
       'Simon Property Group', 'Western Union', 'KeyCorp',
       'Delek US Holdings', 'Booz Allen Hamilton Holding', 'Chemours',
       'Western & Southern Financial Group', 'Regions Financial',
       'Windstream Holdings', 'Seaboard', 'Essendant', 'Apache', 'Airgas',
       'Kelly Services', 'Liberty Media', 'Rockwell Collins',
       'Robert Half International', 'CH2M Hill', 'Big Lots',
       'Michaels Cos.', 'Toll Brothers', 'Yahoo', 'Vistra Energy',
       'ABM I

#Level 3 — Data Cleaning

Before solving these questions, clean these columns:

* Revenues
* Profits
* Assets
* Market Value

Remove:

* $
* commas

Convert them into float.

Then solve:

21. Find the maximum revenue.
22. Find the minimum revenue.
23. Find the average revenue.
24. Find the median revenue.
25. Find the standard deviation of revenue.
26. Find the company having maximum revenue.
27. Find the company having minimum revenue.
28. Find total profits.
29. Find average assets.
30. Find total market value.
31. Find company with highest assets.
32. Find company with lowest assets.
33. Count companies having profit greater than average profit.
34. Count companies having assets greater than average assets.
35. Find top 10 revenues.

In [28]:
clean_data = np.char.replace(np.char.replace(data[:,[4,6,8,9]].astype(str), "$", ""), ",", "")

In [29]:
clean_data[clean_data == '-'] = np.nan

In [30]:
clean_data = clean_data.astype(float)

In [31]:
clean_data[:,0].max()

np.float64(485873.0)

In [32]:
clean_data[:,0].min()

np.float64(5145.0)

In [33]:
clean_data[:,0].mean()

np.float64(24111.748)

In [34]:
np.median(clean_data[:,0])

np.float64(11384.0)

In [35]:
np.std(clean_data[:,0])

np.float64(38298.996795327366)

In [36]:
idx = clean_data[:,0].argmax()
data[idx, 1]

'Walmart'

In [37]:
idx = clean_data[:,0].argmin()
data[idx, 1]

'ABM Industries'

In [38]:
np.nansum(clean_data[:,1])

np.float64(889954.2)

In [39]:
np.nanmean(clean_data[:,2])

np.float64(80389.34)

In [40]:
np.nansum(clean_data[:,3])

np.float64(19421527.0)

In [41]:
np.nanmax(clean_data[:,2])

np.float64(3287968.0)

In [42]:
np.nanmin(clean_data[:,2])

np.float64(437.0)

In [43]:
np.count_nonzero(clean_data[:,3] > np.nanmean(clean_data[:,3]))

np.int64(119)

In [44]:
np.count_nonzero(clean_data[:,2] > np.nanmean(clean_data[:,2]))

np.int64(85)

In [45]:
sort_data = np.sort(clean_data[:,0])

In [46]:
sort_data[-10:]

array([151800., 163786., 166380., 177526., 184840., 192487., 205004.,
       215639., 223604., 485873.])

#Level 4 — Boolean Indexing

36. Companies having revenue greater than 100000.
37. Companies having profits greater than 10000.
38. Companies with market value greater than assets.
39. Companies having employee count greater than 100000.
40. Companies ranked below 50.
41. Companies ranked above 450.
42. Companies with profits less than zero (loss-making).
43. Companies with revenue above average.
44. Companies with assets below average.
45. Companies having market value above average.
46. Companies having profit greater than revenue (if any).
47. Companies whose previous rank is better than current rank.
48. Companies whose previous rank is worse than current rank.
49. Companies whose current rank remained unchanged.
50. Count all three categories above.

In [47]:
revenue = clean_data[:,0]
profits = clean_data[:,1]
assets = clean_data[:,2]
market_value = clean_data[:,3]

In [48]:
rev_great = revenue > 100000
data[rev_great,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding'], dtype=object)

In [49]:
profit = profits > 10000
data[profit,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'AT&T', 'Verizon',
       'Fannie Mae', 'J.P. Morgan Chase', 'Wells Fargo',
       'Bank of America Corp.', 'Alphabet', 'Microsoft', 'Citigroup',
       'IBM', 'Johnson & Johnson', 'Procter & Gamble', 'Intel',
       'Cisco Systems', 'Gilead Sciences', 'Facebook', 'Altria Group'],
      dtype=object)

In [50]:
market_value_greater_than_assets = market_value > assets
data[market_value_greater_than_assets,1]

array(['Walmart', 'Apple', 'Exxon Mobil', 'UnitedHealth Group',
       'Amazon.com', 'Costco', 'Walgreens Boots Alliance', 'Home Depot',
       'Boeing', 'Alphabet', 'Microsoft', 'IBM', 'Johnson & Johnson',
       'Procter & Gamble', 'LoweÕs', 'PepsiCo', 'UPS', 'Intel',
       'United Technologies', 'Disney', 'Humana', 'Pfizer',
       'Lockheed Martin', 'Sysco', 'FedEx', 'Cisco Systems', 'HP',
       'Coca-Cola', 'Merck', 'Best Buy', 'Honeywell International',
       'Oracle', 'TJX', 'Nike', 'General Dynamics', 'Gilead Sciences',
       '3M', 'Time Warner', 'Facebook', 'Twenty-First Century Fox',
       'Philip Morris International', 'Avnet', 'AbbVie', 'McDonaldÕs',
       'DuPont', 'Northrop Grumman', 'Raytheon', 'Qualcomm',
       'Enterprise Products Partners', 'Amgen', 'Dollar General',
       'Starbucks', 'Eli Lilly', 'Abbott Laboratories', 'Dollar Tree',
       'Southwest Airlines', 'Emerson Electric', 'Union Pacific',
       'Danaher', 'Bristol-Myers Squibb', 'Altria Group',
  

In [51]:
No_of_employees = np.char.replace(data[:,2].astype(str), ",", "").astype(float)

employee_count = No_of_employees > 100000
data[employee_count,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'UnitedHealth Group',
       'CVS Health', 'General Motors', 'AT&T', 'Ford Motor', 'Amazon.com',
       'General Electric', 'Verizon', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'J.P. Morgan Chase',
       'Home Depot', 'Boeing', 'Wells Fargo', 'Bank of America Corp.',
       'Microsoft', 'Citigroup', 'Comcast', 'IBM', 'Johnson & Johnson',
       'Procter & Gamble', 'Target', 'LoweÕs', 'Dell Technologies',
       'PepsiCo', 'UPS', 'Intel', 'Albertsons Cos.',
       'United Technologies', 'Disney', 'FedEx',
       'Hewlett Packard Enterprise', 'HCA Holdings', 'Coca-Cola',
       'American Airlines Group', 'Best Buy', 'Honeywell International',
       'Oracle', 'Tyson Foods', 'Publix Super Markets', 'TJX', 'MacyÕs',
       'McDonaldÕs', 'Sears Holdings', 'Dollar General',
       'Community Health Systems', 'Starbucks', 'Tenet Healthcare',
       'Dollar Tree', 'Emerson Electric', 'Lear', 'Jabil Circuit',
       'Xerox', 'Marrio

In [52]:
rank = data[:,0].astype(float)

companies_rank_below_50 = rank < 50
data[companies_rank_below_50, 1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.'], dtype=object)

In [53]:
companies_rank_above_450 = rank > 450
data[companies_rank_above_450, 1]

array(['Citizens Financial Group', 'United Rentals', 'Clorox',
       'Genesis Healthcare', 'M&T Bank Corp.', 'Ingredion', 'UGI',
       'Owens Corning', 'S&P Global', 'Markel', 'Wyndham Worldwide',
       'Arthur J. Gallagher', 'Burlington Stores',
       'First American Financial', 'Symantec', 'Patterson', 'Olin',
       'NetApp', 'Raymond James Financial', 'TravelCenters of America',
       'Fiserv', 'Host Hotels & Resorts', 'Insight Enterprises', 'Mattel',
       'AmTrust Financial Services', 'Cincinnati Financial',
       'Simon Property Group', 'Western Union', 'KeyCorp',
       'Delek US Holdings', 'Booz Allen Hamilton Holding', 'Chemours',
       'Western & Southern Financial Group', 'Regions Financial',
       'Windstream Holdings', 'Seaboard', 'Essendant', 'Apache', 'Airgas',
       'Kelly Services', 'Liberty Media', 'Rockwell Collins',
       'Robert Half International', 'CH2M Hill', 'Big Lots',
       'Michaels Cos.', 'Toll Brothers', 'Yahoo', 'Vistra Energy',
       'ABM I

In [54]:
loss_making_companies = profits < 0
data[loss_making_companies, 1]

array(['Chevron', 'Dell Technologies', 'Albertsons Cos.', 'AIG',
       'Caterpillar', 'ConocoPhillips', 'Sears Holdings',
       'Community Health Systems', 'Tenet Healthcare', 'Staples', 'Xerox',
       'Icahn Enterprises', 'Halliburton', 'Freeport-McMoRan', 'WestRock',
       'AES', 'FirstEnergy', 'ConAgra Foods',
       'Farmers Insurance Exchange', 'Micron Technology', 'Alcoa',
       'NRG Energy', 'Devon Energy', 'NGL Energy Partners', 'Toys ÒRÓ Us',
       'Entergy', 'Voya Financial', 'HollyFrontier',
       'Occidental Petroleum', 'United States Steel', 'Baker Hughes',
       'Hertz Global Holdings', 'Alcoa', 'Frontier Communications',
       'Newmont Mining', 'Genworth Financial', 'Global Partners',
       'Navistar International', 'Univar', 'Chesapeake Energy',
       'Anadarko Petroleum', 'EOG Resources', 'Williams',
       'National Oilwell Varco', 'Kindred Healthcare', 'Tesla',
       'Ascena Retail Group', 'R.R. Donnelley & Sons', 'Targa Resources',
       'HRG Group', 'i

In [55]:
companies_above_average_revenue = revenue > np.nanmean(revenue)
data[companies_above_average_revenue, 1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.', 'United Technologies', 'Marathon Petroleum',
       'Disney', 'Humana', 'Pfizer', 'AIG', 'Lockheed Martin', 'Sysco',
       'FedEx', 'Hewlett Packard Ente

In [56]:
companies_below_average_assets = assets < np.nanmean(assets)
data[companies_below_average_assets, 1]

array(['McKesson', 'AmerisourceBergen', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Express Scripts Holding',
       'Home Depot', 'Anthem', 'Phillips 66', 'Valero Energy', 'Target',
       'LoweÕs', 'Aetna', 'PepsiCo', 'Archer Daniels Midland', 'UPS',
       'Albertsons Cos.', 'Marathon Petroleum', 'Humana',
       'Lockheed Martin', 'Sysco', 'FedEx', 'Hewlett Packard Enterprise',
       'HP', 'Dow Chemical', 'HCA Holdings', 'Centene',
       'American Airlines Group', 'Cigna', 'Delta Air Lines', 'Best Buy',
       'Honeywell International', 'Caterpillar', 'Energy Transfer Equity',
       'Tyson Foods', 'United Continental Holdings',
       'Publix Super Markets', 'TJX', 'Nike', 'General Dynamics',
       'Rite Aid', 'Gilead Sciences', 'CHS', '3M', 'Time Warner',
       'Facebook', 'Twenty-First Century Fox', 'World Fuel Services',
       'Philip Morris International', 'Deere', 'Tech Data', 'Avnet',
       'Avnet', 'MacyÕs', 'AbbVie', 'McDonaldÕs', 'DuPo

In [57]:
companies_above_average_market_value = market_value > np.nanmean(market_value)
data[companies_above_average_market_value, 1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'UnitedHealth Group', 'CVS Health', 'General Motors', 'AT&T',
       'Ford Motor', 'Amazon.com', 'General Electric', 'Verizon',
       'Costco', 'Walgreens Boots Alliance', 'Chevron',
       'J.P. Morgan Chase', 'Home Depot', 'Boeing', 'Wells Fargo',
       'Bank of America Corp.', 'Alphabet', 'Microsoft', 'Anthem',
       'Citigroup', 'Comcast', 'IBM', 'Johnson & Johnson',
       'Procter & Gamble', 'LoweÕs', 'MetLife', 'Aetna', 'PepsiCo', 'UPS',
       'Intel', 'Prudential Financial', 'United Technologies', 'Disney',
       'Pfizer', 'AIG', 'Lockheed Martin', 'FedEx', 'Cisco Systems',
       'Dow Chemical', 'Coca-Cola', 'Merck', 'Honeywell International',
       'Caterpillar', 'Morgan Stanley', 'Goldman Sachs Group', 'Oracle',
       'American Express', 'TJX', 'Nike', 'General Dynamics',
       'Gilead Sciences', '3M', 'Time Warner', 'Charter Communications',
       'Facebook', 'Capital One Financial', 'Twenty-Fir

In [58]:
companies_having_profit_greater_than_revenue = profits > revenue
data[companies_having_profit_greater_than_revenue, 1]

array([], dtype=object)

In [59]:
prev_rank = data[:, 3].astype(float)

worsen_companies = rank < prev_rank
data[worsen_companies,1]

array(['Berkshire Hathaway', 'AT&T', 'AmerisourceBergen', 'Amazon.com',
       'Cardinal Health', 'Walgreens Boots Alliance', 'J.P. Morgan Chase',
       'Home Depot', 'Wells Fargo', 'Alphabet', 'Anthem', 'Comcast',
       'State Farm Insurance Cos.', 'Johnson & Johnson', 'Freddie Mac',
       'LoweÕs', 'Aetna', 'UPS', 'Intel', 'Prudential Financial',
       'Disney', 'Pfizer', 'Lockheed Martin', 'Centene', 'Nationwide',
       'Merck', 'Cigna', 'Honeywell International', 'Morgan Stanley',
       'TIAA', 'Publix Super Markets', 'TJX', 'Nike', 'Exelon',
       'Rite Aid', 'Time Warner', 'Charter Communications',
       'Northwestern Mutual', 'Facebook', 'Travelers Cos.',
       'Capital One Financial', 'USAA', 'Philip Morris International',
       'Kraft Heinz', 'Tech Data', 'AbbVie', 'Northrop Grumman',
       'Raytheon', 'Arrow Electronics', 'Progressive', 'Amgen',
       'U.S. Bancorp', 'Aflac', 'Dollar General', 'AutoNation',
       'Starbucks', 'Eli Lilly', 'Tenet Healthcare',
    

In [60]:
improved_companies = rank > prev_rank
data[improved_companies,1]

array(['Exxon Mobil', 'Ford Motor', 'General Electric', 'Verizon',
       'Costco', 'Kroger', 'Chevron', 'Fannie Mae', 'Microsoft',
       'Citigroup', 'IBM', 'Phillips 66', 'Procter & Gamble',
       'Valero Energy', 'MetLife', 'Archer Daniels Midland',
       'United Technologies', 'Marathon Petroleum', 'Humana', 'AIG',
       'Cisco Systems', 'HP', 'Dow Chemical', 'Coca-Cola',
       'New York Life Insurance', 'Delta Air Lines', 'Best Buy',
       'Caterpillar', 'Liberty Mutual Insurance Group',
       'Massachusetts Mutual Life Insurance', 'Goldman Sachs Group',
       'Energy Transfer Equity', 'Oracle', 'Tyson Foods',
       'United Continental Holdings', 'Allstate', 'American Express',
       'General Dynamics', 'Gilead Sciences', 'CHS', '3M',
       'Twenty-First Century Fox', 'World Fuel Services', 'Deere',
       'Avnet', 'Avnet', 'MacyÕs', 'McDonaldÕs', 'DuPont',
       'ConocoPhillips', 'Tesoro', 'Qualcomm', 'Duke Energy',
       'Enterprise Products Partners', 'US Foods Hol

In [61]:
No_rank_changed_companies = rank == prev_rank
data[No_rank_changed_companies,1]

array(['Walmart', 'Apple', 'McKesson', 'UnitedHealth Group', 'CVS Health',
       'General Motors', 'Express Scripts Holding', 'Boeing',
       'Bank of America Corp.', 'Target', 'PepsiCo', 'Sysco', 'FedEx',
       'HCA Holdings', 'American Airlines Group', 'Freeport-McMoRan',
       'Auto-Owners Insurance', 'NCR', 'Ingredion',
       'Host Hotels & Resorts', 'Big Lots'], dtype=object)

In [62]:
data[worsen_companies,1].size

262

In [63]:
data[improved_companies,1].size

209

In [64]:
data[No_rank_changed_companies,1].size

21

#Level 5 — NumPy Functions

51. Sort companies by revenue.
52. Sort companies by profits.
53. Sort companies by market value.
54. Find indices of top 10 revenues.
55. Find indices of top 20 profits.
56. Find bottom 20 market values.
57. Use np.argsort() to sort companies by assets.
58. Use np.argmin() to find lowest revenue company.
59. Use np.argmax() to find highest market value company.
60. Find second highest revenue.
61. Find third highest profit.
62. Find top 5 assets.
63. Find bottom 5 assets.
64. Count NaN values (if any).
65. Replace NaN values using NumPy.

In [65]:
revenue_sort = np.argsort(revenue)
data[revenue_sort]

array([[500, 'ABM Industries', '1,10,000', ..., '-25.0%', '$2,281',
        '$2,428'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968'],
       [498, 'Yahoo', '8,500', ..., '-', '$48,083', '$44,391'],
       ...,
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [2, 'Berkshire Hathaway', '3,67,700', ..., '0.0%', '$6,20,854',
        '$4,11,035'],
       [1, 'Walmart', '23,00,000', ..., '-7.2%', '$1,98,825',
        '$2,18,619']], shape=(500, 10), dtype=object)

In [66]:
profit_sort = np.argsort(profits)
data[profit_sort]

array([[196, 'FirstEnergy', '15,707', ..., '-', '$43,148', '$14,118'],
       [173, 'Halliburton', '50,000', ..., '-', '$27,000', '$42,662'],
       [343, 'Chesapeake Energy', '3,300', ..., '-', '$13,028', '$5,394'],
       ...,
       [21, 'J.P. Morgan Chase', '2,43,355', ..., '1.2%', '$24,90,972',
        '$3,13,761'],
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968']],
      shape=(500, 10), dtype=object)

In [67]:
sort_market_value = np.argsort(market_value)
data[sort_market_value]

array([[395, 'A-Mark Precious Metals', '83,000', ..., '31.5%', '$437',
        '$120'],
       [470, 'TravelCenters of America', '20,259', ..., '-107.3%',
        '$1,660', '$241'],
       [426, 'iHeartMedia', '18,700', ..., '-', '$12,862', '$330'],
       ...,
       [382, 'Erie Insurance Group', '4,988', ..., '10.7%', '$18,417',
        '-'],
       [244, 'Toys ÒRÓ Us', '64,000', ..., '-', '$6,908', '-'],
       [420, 'Graybar Electric', '8,500', ..., '2.2%', '$2,099', '-']],
      shape=(500, 10), dtype=object)

In [68]:
top_10_revenue = np.argsort(revenue)[-10:]
top_10_revenue

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [69]:
top_20_profit = np.argsort(profits)[-20:]
top_20_profit

array([ 46,  35,  59,  31,  19,   8,  13,  91,   0, 147,  29,  34,  27,
        25,  26,  24,   1,  20,   2, 498])

In [70]:
bottom_20_market_value = np.argsort(market_value)[:20]
data[bottom_20_market_value]

array([[395, 'A-Mark Precious Metals', '83,000', 426.0, '$6,784',
        '11.8%', '$9.3', '31.5%', '$437', '$120'],
       [470, 'TravelCenters of America', '20,259', 439.0, '$5,511',
        '-5.8%', '-$2.0', '-107.3%', '$1,660', '$241'],
       [426, 'iHeartMedia', '18,700', 414.0, '$6,274', '0.5%', '-$296.3',
        '-', '$12,862', '$330'],
       [454, 'Genesis Healthcare', '82,000', 457.0, '$5,733', '2.0%',
        '-$64.0', '-', '$5,779', '$408'],
       [487, 'Essendant', '6,600', 477.0, '$5,369', '0.1%', '$63.9', '-',
        '$2,164', '$568'],
       [334, 'Global Partners', '1,770', 276.0, '$8,240', '-20.1%',
        '-$199.4', '-557.8%', '$2,564', '$663'],
       [189, 'INTL FCStone', '1,464', 83.0, '$14,755', '-57.5%', '$54.7',
        '-1.8%', '$5,951', '$708'],
       [376, 'Kindred Healthcare', '76,650', 372.0, '$7,227', '1.8%',
        '-$664.2', '-', '$6,113', '$711'],
       [331, 'Veritiv', '8,700', 323.0, '$8,327', '-4.5%', '$21.0',
        '-21.3%', '$2,484', '$8

In [71]:
Sort_assets = np.argsort(assets)
data[Sort_assets]

array([[395, 'A-Mark Precious Metals', '83,000', ..., '31.5%', '$437',
        '$120'],
       [247, 'Core-Mark Holding', '7,688', ..., '5.2%', '$1,497',
        '$1,445'],
       [495, 'Big Lots', '23,150', ..., '7.0%', '$1,608', '$2,180'],
       ...,
       [26, 'Bank of America Corp.', '2,08,024', ..., '12.7%',
        '$21,87,702', '$2,36,182'],
       [21, 'J.P. Morgan Chase', '2,43,355', ..., '1.2%', '$24,90,972',
        '$3,13,761'],
       [20, 'Fannie Mae', '7,000', ..., '12.4%', '$32,87,968', '$3,011']],
      shape=(500, 10), dtype=object)

In [72]:
lowest_revenue_company = np.argmin(revenue)
data[lowest_revenue_company]

array([500, 'ABM Industries', '1,10,000', 485.0, '$5,145', '-2.8%',
       '$57.2', '-25.0%', '$2,281', '$2,428'], dtype=object)

In [73]:
highest_market_value_company = np.argmax(market_value)
data[highest_market_value_company]

array([33, 'State Farm Insurance Cos.', '68,234', 35.0, '$76,132', '0.6%',
       '$350.3', '-94.4%', '$2,56,030', '-'], dtype=object)

In [74]:
data[np.argsort(revenue)[-2]]

array([2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
       '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'], dtype=object)

In [75]:
data[np.argsort(profits)[-3]]

array([21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
       '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'], dtype=object)

In [76]:
data[np.argsort(assets)[-5:]]

array([[25, 'Wells Fargo', '2,69,100', 27.0, '$94,176', '4.6%',
        '$21,938.0', '-4.2%', '$19,30,115', '$2,78,516'],
       [39, 'Freddie Mac', '5,982', 43.0, '$65,665', '3.4%', '$7,815.0',
        '22.6%', '$20,23,376', '$1,612'],
       [26, 'Bank of America Corp.', '2,08,024', 26.0, '$93,662', '0.7%',
        '$17,906.0', '12.7%', '$21,87,702', '$2,36,182'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [20, 'Fannie Mae', '7,000', 16.0, '$1,07,162', '-2.9%',
        '$12,313.0', '12.4%', '$32,87,968', '$3,011']], dtype=object)

In [77]:
data[np.argsort(assets)[:5]]

array([[395, 'A-Mark Precious Metals', '83,000', 426.0, '$6,784',
        '11.8%', '$9.3', '31.5%', '$437', '$120'],
       [247, 'Core-Mark Holding', '7,688', 317.0, '$11,507', '29.9%',
        '$54.2', '5.2%', '$1,497', '$1,445'],
       [495, 'Big Lots', '23,150', 495.0, '$5,200', '0.2%', '$152.8',
        '7.0%', '$1,608', '$2,180'],
       [470, 'TravelCenters of America', '20,259', 439.0, '$5,511',
        '-5.8%', '-$2.0', '-107.3%', '$1,660', '$241'],
       [493, 'Robert Half International', '16,400', 503.0, '$5,250',
        '3.1%', '$343.4', '-4.0%', '$1,778', '$6,240']], dtype=object)

In [78]:
np.count_nonzero(np.isnan(clean_data))

np.int64(31)

In [79]:
for i in range(clean_data.shape[1]):
    column = clean_data[:, i]

    # find NaN values
    mask = np.isnan(column)

    # calculate column mean
    mean = np.nanmean(column)

    # replace NaN
    column[mask] = mean

# Level 6 — Advanced NumPy

66. Normalize revenues using Min-Max Scaling.
67. Standardize profits using Z-score normalization.
68. Create a NumPy array containing only:
- Revenue
- Profit
- Assets
69. Compute column-wise mean.
70. Compute row-wise mean.
71. Compute covariance matrix.
72. Compute correlation matrix.
73. Find percentile values:
- 25th
- 50th
- 75th
74. Find Interquartile Range (IQR).
75. Detect revenue outliers using IQR.
76. Detect profit outliers.
77. Find revenue quartiles.
78. Split data into 5 equal chunks using NumPy.
79. Randomly sample 25 companies.
80. Shuffle the dataset using NumPy.

In [80]:
revenue_scaled = (revenue - np.nanmin(revenue))/(np.nanmax(revenue)-np.nanmin(revenue))
revenue_scaled

array([1.00000000e+00, 4.54433692e-01, 4.37865071e-01, 4.15742374e-01,
       3.89704781e-01, 3.73797657e-01, 3.58583232e-01, 3.35397564e-01,
       3.30001581e-01, 3.05068563e-01, 2.94771680e-01, 2.72174702e-01,
       2.52774958e-01, 2.51358356e-01, 2.42134845e-01, 2.36254181e-01,
       2.33408497e-01, 2.29219018e-01, 2.13056032e-01, 2.12213559e-01,
       2.08727180e-01, 1.97914413e-01, 1.86071958e-01, 1.86022033e-01,
       1.85200363e-01, 1.84131151e-01, 1.77079346e-01, 1.66778303e-01,
       1.65827661e-01, 1.60675059e-01, 1.56550066e-01, 1.55543259e-01,
       1.47665624e-01, 1.39894077e-01, 1.38841507e-01, 1.38500358e-01,
       1.35255279e-01, 1.33859480e-01, 1.25892397e-01, 1.24544441e-01,
       1.24105523e-01, 1.21338886e-01, 1.20671149e-01, 1.19930605e-01,
       1.18988284e-01, 1.15992828e-01, 1.12833037e-01, 1.11568288e-01,
       1.11474680e-01, 1.08375214e-01, 1.05492087e-01, 1.05021967e-01,
       1.02415503e-01, 9.91808257e-02, 9.82301842e-02, 9.46751593e-02,
      

In [81]:
profits_z_score = (profits - np.nanmean(profits))/np.nanstd(profits)
profits_z_score

array([ 3.01569067e+00,  5.66812998e+00,  1.11639761e+01,  1.54007900e+00,
        1.20664158e-01,  1.33080304e+00,  8.98519766e-01,  1.94362815e+00,
        2.84608305e+00,  7.15180801e-01, -9.04172215e-02,  1.49398281e-01,
        1.79207472e+00,  2.88447998e+00, -9.06460773e-02,  1.44058312e-01,
        6.07618551e-01,  4.87017072e-02, -5.79889029e-01,  2.67749258e+00,
        5.83570332e+00,  4.12175655e-01,  1.56983026e+00,  7.91211800e-01,
        5.12497876e+00,  4.09970455e+00,  4.49943943e+00,  3.81795757e+00,
        1.74521568e-01,  3.33837742e+00,  1.75749206e+00,  2.56535321e+00,
       -3.64433960e-01, -5.80976897e-02,  3.75235222e+00,  2.21850945e+00,
        1.28546971e-01,  2.42466327e-01,  1.53372189e+00,  3.32991531e-01,
       -8.78673056e-01, -2.50082320e-01,  1.23969854e-01,  1.15585546e+00,
       -1.28280151e-01,  4.18939617e-01,  2.16968687e+00,  6.57203985e-01,
       -5.81211307e-01,  8.31897285e-01, -1.54980000e-01,  1.93447392e+00,
       -2.97379196e-01,  

In [82]:
New_array = np.array(clean_data[:,0:3])

In [83]:
np.nanmean(New_array, axis=0)

array([24111.748    ,  1783.4753507, 80389.34     ])

In [84]:
np.nanmean(New_array, axis=1)

array([ 232780.33333333,  289510.66666667,  194337.33333333,
        181052.66666667,   83769.33333333,  104889.        ,
         92435.        ,  132499.        ,  193527.66666667,
        131449.        ,   60644.63333333,   73920.        ,
        166891.66666667,  127762.33333333,   52365.        ,
         51410.66666667,   64737.33333333,   51272.33333333,
        122382.66666667, 1135814.33333333,  873730.33333333,
         51812.46666667,   48506.        ,   63154.33333333,
        682076.33333333,  766423.33333333,   92415.66666667,
         98604.        ,   50805.26666667,  629791.66666667,
         89866.        ,   69753.66666667,  110837.43333333,
         41868.        ,   76546.        ,   69790.        ,
         39542.66666667,   36554.33333333,  698952.        ,
         34172.66666667,   60446.66666667,  321013.33333333,
         44857.33333333,   47752.33333333,   34464.66666667,
         34904.66666667,   61010.        ,  282369.66666667,
         27333.93333333,

In [85]:
np.cov(New_array.T)

array([[1.46975266e+09, 9.05335963e+07, 3.41962817e+09],
       [9.05335963e+07, 1.54963865e+07, 5.45670574e+08],
       [3.41962817e+09, 5.45670574e+08, 7.31300597e+10]])

In [86]:
np.corrcoef(New_array.T)

array([[1.        , 0.59989111, 0.32984416],
       [0.59989111, 1.        , 0.51258672],
       [0.32984416, 0.51258672, 1.        ]])

In [87]:
# Q1
revenue_q1 = np.nanpercentile(New_array[:,0], 25)

In [88]:
# Q2
revenue_q2 = np.nanpercentile(New_array[:,0], 50)

In [89]:
# Q3
revenue_q3 = np.nanpercentile(New_array[:,0], 75)

In [90]:
# IQR formula = Q3 - Q1
IQR = revenue_q3 - revenue_q1
IQR

np.float64(15360.25)

In [91]:
# Lower boundary
revenue_lower_boundary = revenue_q1 - 1.5 * IQR

# Upper boundary
revenue_upper_boundary = revenue_q3 + 1.5 * IQR

# Oultier
revenue_outlier = (revenue < revenue_lower_boundary) | (revenue > revenue_upper_boundary)

data[revenue_outlier,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.', 'United Technologies', 'Marathon Petroleum',
       'Disney', 'Humana', 'Pfizer', 'AIG', 'Lockheed Martin', 'Sysco',
       'FedEx', 'Hewlett Packard Ente

In [92]:
# Q1
profits_q1 = np.nanpercentile(New_array[:,1], 25)

# Q3
profits_q3 = np.nanpercentile(New_array[:,1], 75)

# IQR
profits_IQR = profits_q3 - profits_q1

# Lower boundary
profits_lower_boundary = profits_q1 - 1.5 * profits_IQR

# Upper boundary
profits_upper_boundary = profits_q3 + 1.5 * profits_IQR

# Outliers
profits_outlier = (profits < profits_lower_boundary) | (profits > profits_upper_boundary)

data[profits_outlier, 1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'UnitedHealth Group', 'CVS Health', 'General Motors', 'AT&T',
       'Ford Motor', 'General Electric', 'Verizon',
       'Walgreens Boots Alliance', 'Fannie Mae', 'J.P. Morgan Chase',
       'Home Depot', 'Boeing', 'Wells Fargo', 'Bank of America Corp.',
       'Alphabet', 'Microsoft', 'Citigroup', 'Comcast', 'IBM',
       'Johnson & Johnson', 'Procter & Gamble', 'Freddie Mac', 'PepsiCo',
       'Intel', 'Prudential Financial', 'United Technologies', 'Disney',
       'Pfizer', 'Lockheed Martin', 'Cisco Systems', 'Dow Chemical',
       'Coca-Cola', 'Delta Air Lines', 'Honeywell International',
       'Morgan Stanley', 'Goldman Sachs Group', 'Oracle',
       'American Express', 'Gilead Sciences', '3M', 'Facebook',
       'Philip Morris International', 'AbbVie', 'McDonaldÕs',
       'ConocoPhillips', 'Qualcomm', 'Amgen', 'U.S. Bancorp',
       'Sears Holdings', 'Union Pacific', 'Bristol-Myers Squibb',
       'Altria Gr

In [93]:
revenue_quartile = np.nanpercentile(New_array[:,0],[0,25,50,75, 100])
revenue_quartile

array([  5145.  ,   7245.  ,  11384.  ,  22605.25, 485873.  ])

In [94]:
np.array_split(data, 5)

[array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
         '-7.2%', '$1,98,825', '$2,18,619'],
        [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
         '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
        [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
         '-14.4%', '$3,21,686', '$7,53,718'],
        [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004', '-16.7%',
         '$7,840.0', '-51.5%', '$3,30,314', '$3,40,056'],
        [5, 'McKesson', '68,000', 5.0, '$1,92,487', '6.2%', '$2,258.0',
         '53.0%', '$56,563', '$31,439'],
        [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
         '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
        [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526', '15.8%',
         '$5,317.0', '1.5%', '$94,462', '$81,310'],
        [8, 'General Motors', '2,25,000', 8.0, '$1,66,380', '9.2%',
         '$9,427.0', '-2.7%', '$2,21,690', '$52,968'],
        [9, 'AT&T', '2,68,

In [95]:
rng = np.random.default_rng(seed=42)
rng.choice(data, size=25, axis=0, replace = False)

array([[337, 'Navistar International', '11,300', 281.0, '$8,111',
        '-20.0%', '-$97.0', '-', '$5,653', '$2,416'],
       [185, 'Synchrony Financial', '15,000', nan, '$15,122', '11.0%',
        '$2,251.0', '1.7%', '$90,207', '$27,810'],
       [98, 'Facebook', '17,048', 157.0, '$27,638', '54.2%', '$10,217.0',
        '177.0%', '$64,961', '$4,10,522'],
       [391, 'Jones Lang LaSalle', '77,300', 436.0, '$6,804', '14.0%',
        '$318.2', '-27.5%', '$7,629', '$5,043'],
       [91, 'Rite Aid', '70,580', 107.0, '$30,737', '15.9%', '$165.5',
        '-92.2%', '$11,277', '$4,473'],
       [386, 'Harman International Industries', '26,000', 419.0,
        '$6,912', '12.3%', '$361.7', '5.6%', '$6,054', '-'],
       [313, 'Frontier Communications', '28,332', 461.0, '$8,896',
        '59.5%', '-$373.0', '-', '$29,013', '$2,521'],
       [413, 'Berry Global Group', '21,000', 518.0, '$6,489', '32.9%',
        '$236.0', '174.4%', '$7,653', '$6,256'],
       [373, 'WESCO International', '9,000

In [96]:
# It shuffles the data permanently.
np.random.shuffle(data)

# Level 7 — Interview Challenge

81. Find the top 10 companies by revenue without using Pandas sorting.
82. Find the top 10 companies by profit.
83. Find the richest company by market value.
84. Find the company having the largest assets.
85. Find average employee count.
86. Find the company closest to the average revenue.
87. Find the company farthest from average revenue.
88. Compute revenue-to-assets ratio.
89. Compute profit margin:
    * Profit Margin = Profit / Revenue

90. Find top 20 companies by profit margin.
91. Find companies with the highest revenue per employee.
92. Find companies with the highest assets per employee.
93. Create a ranking based on profits only.
94. Create a ranking based on market value only.
95. Compare current rank vs profit rank.
96. Find companies whose profit rank is better than their Fortune rank.
97. Find companies whose revenue rank differs by more than 100 positions from their Fortune rank.
98. Find the top 5 companies that dominate in:
 - Revenue
 - Profit
 - Assets
 - Market Value
99. Build a NumPy-only summary table containing:
 - Mean
 - Median
 - Max
 - Min
 - Std

for Revenue, Profit, Assets, and Market Value.

100. Without using any Pandas analytical functions (only Pandas for loading), reproduce a mini statistical report similar to describe() using only NumPy.

In [97]:
df = pd.read_csv('/Users/krishnag02/Learning Phase/Jupyterfiles/Fortune_500.csv', encoding='latin-1')
df.head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"


In [98]:
data = df.to_numpy()

In [99]:
# Ques 81
data[np.argsort(clean_data[:,0]),1][-10:]

array(['Ford Motor', 'AT&T', 'General Motors', 'CVS Health',
       'UnitedHealth Group', 'McKesson', 'Exxon Mobil', 'Apple',
       'Berkshire Hathaway', 'Walmart'], dtype=object)

In [100]:
# Ques 82
data[np.argsort(clean_data[:,1]),1][-10:]

array(['Altria Group', 'Citigroup', 'Johnson & Johnson', 'Microsoft',
       'Bank of America Corp.', 'Alphabet', 'Wells Fargo',
       'Berkshire Hathaway', 'J.P. Morgan Chase', 'Apple'], dtype=object)

In [101]:
# Ques 83
data[np.argmax(clean_data[:,3]),1]

'Apple'

In [102]:
# Ques 84
data[np.argmax(clean_data[:,2]),1]

'Fannie Mae'

In [103]:
# Ques 85
np.nanmean(No_of_employees)

np.float64(56955.526)

In [104]:
# Ques 86
average_revenue = np.nanmean(clean_data[:,0])

difference = np.abs(clean_data[:,0]-average_revenue)

mask = np.argmin(difference)

data[mask]

array([116, 'Raytheon', '63,000', 120.0, '$24,069', '3.5%', '$2,211.0',
       '6.6%', '$30,052', '$44,664'], dtype=object)

In [105]:
# Ques 87
mask = np.argmax(difference)

data[mask]

array([1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
       '-7.2%', '$1,98,825', '$2,18,619'], dtype=object)

In [106]:
# Ques 88
revenue_to_assets_ratio = revenue/assets
revenue_to_assets_ratio

array([ 2.44372187,  0.36015553,  0.67034002,  0.6206337 ,  3.403055  ,
        1.50508916,  1.87933772,  0.75050747,  0.4055906 ,  0.63794647,
        4.36326361,  1.63050047,  0.34684254,  0.51593087,  3.5621007 ,
        3.5798631 ,  1.61444805,  3.159485  ,  0.41359515,  0.03259217,
        0.04234732,  1.93811963,  2.20162454,  1.05082392,  0.04879295,
        0.04281296,  0.53894697,  0.44048861,  1.30391961,  0.04597235,
        0.44544598,  0.6803354 ,  0.29735578,  1.40158364,  0.50910713,
        0.56416751,  1.51963269,  1.85661617,  0.03245319,  1.88958963,
        0.54824628,  0.07062588,  0.91335724,  0.84715833,  1.56770349,
        1.50843302,  0.52403223,  0.07497685,  2.47092974,  0.638129  ,
        1.25769482,  0.60447883,  2.14124272,  0.30780526,  0.1050989 ,
        1.05965778,  3.01202009,  1.09337009,  0.62906161,  0.40481866,
        1.66280593,  0.6056772 ,  1.32552284,  0.4796952 ,  0.14201799,
        2.01619052,  0.78363303,  0.20260883,  0.41736477,  0.66

In [107]:
# Ques 89
profit_margin = profits/revenue
profit_margin

array([ 2.80793541e-02,  1.07663548e-01,  2.11867983e-01,  3.82431562e-02,
        1.17306623e-02,  3.79625622e-02,  2.99505425e-02,  5.66594543e-02,
        7.92253306e-02,  3.02766798e-02,  9.72352741e-03,  1.74354902e-02,
        6.97215402e-02,  1.04199079e-01,  1.17404110e-02,  1.97946411e-02,
        3.55599867e-02,  1.71237331e-02, -4.62037614e-03,  1.14900804e-01,
        2.34467133e-01,  3.39462348e-02,  8.41164966e-02,  5.17600533e-02,
        2.32946823e-01,  1.91176785e-01,  2.15770117e-01,  1.96882325e-01,
        2.91033784e-02,  1.81001626e-01,  1.08142731e-01,  1.48550407e-01,
        4.60121894e-03,  2.14790872e-02,  2.30073724e-01,  1.46501966e-01,
        3.26226377e-02,  3.93841284e-02,  1.19013173e-01,  4.75721734e-02,
       -2.58000802e-02,  1.26031886e-02,  3.59591481e-02,  1.00781860e-01,
        2.05145478e-02,  5.63327094e-02,  1.73708051e-01,  7.43122544e-02,
       -8.55041373e-03,  8.83061980e-02,  2.10175803e-02,  1.68805723e-01,
        1.12911234e-02,  

In [108]:
# Ques 90
data[np.argsort(profit_margin)][-20:]

array([[125, 'U.S. Bancorp', '71,191', 131.0, '$22,744', '5.8%',
        '$5,888.0', '0.2%', '$4,45,964', '$87,201'],
       [405, 'Franklin Resources', '9,059', 344.0, '$6,618', '-16.7%',
        '$1,726.7', '-15.2%', '$16,099', '$23,823'],
       [104, 'Philip Morris International', '79,500', 106.0, '$26,685',
        '-0.4%', '$6,967.0', '1.4%', '$36,851', '$1,75,349'],
       [206, 'Texas Instruments', '29,865', 219.0, '$13,370', '2.8%',
        '$3,595.0', '20.4%', '$16,431', '$80,531'],
       [255, 'BlackRock', '13,000', 250.0, '$11,155', '-2.2%',
        '$3,172.0', '-5.2%', '$2,20,177', '$62,225'],
       [248, 'Biogen', '7,400', 263.0, '$11,449', '6.4%', '$3,702.8',
        '4.4%', '$22,877', '$59,046'],
       [123, 'Amgen', '19,200', 130.0, '$22,991', '6.1%', '$7,722.0',
        '11.3%', '$77,626', '$1,20,830'],
       [477, 'Simon Property Group', '4,050', 488.0, '$5,435', '3.2%',
        '$1,838.9', '0.6%', '$31,104', '$53,732'],
       [499, 'Vistra Energy', '4,431', nan

In [109]:
# Ques 91
revenue_per_employee = revenue/No_of_employees

data[np.argmax(revenue_per_employee)]

array([20, 'Fannie Mae', '7,000', 16.0, '$1,07,162', '-2.9%', '$12,313.0',
       '12.4%', '$32,87,968', '$3,011'], dtype=object)

In [110]:
# Ques 92
assets_per_employee = assets/No_of_employees

data[np.argmax(assets_per_employee)]

array([20, 'Fannie Mae', '7,000', 16.0, '$1,07,162', '-2.9%', '$12,313.0',
       '12.4%', '$32,87,968', '$3,011'], dtype=object)

In [111]:
# Ques 93
profit_order = np.argsort(profits)[::-1]
profit_rank = np.arange(1, len(profit_order)+1)
companies = data[profit_order, 1]
profit = profits[profit_order]

result = np.column_stack((profit_rank, companies, profit))
result

array([[1, 'Apple', 45687.0],
       [2, 'J.P. Morgan Chase', 24733.0],
       [3, 'Berkshire Hathaway', 24074.0],
       ...,
       [498, 'Chesapeake Energy', -4401.0],
       [499, 'Halliburton', -5763.0],
       [500, 'FirstEnergy', -6177.0]], shape=(500, 3), dtype=object)

In [112]:
# Ques 94
market_value_order = np.argsort(market_value)[::-1]
market_value_rank = np.arange(1,len(market_value_order)+1)
companies_market_value = data[market_value_order,1]
market_val = market_value[market_value_order]

result = np.column_stack((market_value_rank, companies_market_value, market_val))
result

array([[1, 'Apple', 753718.0],
       [2, 'Alphabet', 579426.0],
       [3, 'Microsoft', 508935.0],
       ...,
       [498, 'iHeartMedia', 330.0],
       [499, 'TravelCenters of America', 241.0],
       [500, 'A-Mark Precious Metals', 120.0]],
      shape=(500, 3), dtype=object)

In [113]:
# Ques 95
# Step1: rank according to profit
profit_order = np.argsort(profits)[::-1]
profit_rank = np.arange(1,len(profit_order)+1)

companies = data[profit_order, 1]

# Step2: find original rank according to profit_order
original_rank = data[profit_order, 0]

# Step3: combine
compare_profit_original = np.column_stack((profit_rank, original_rank, companies))


In [114]:
# Ques 96
compare_profit_original[compare_profit_original[:,0] < compare_profit_original[:,1]]

array([[1, 3, 'Apple'],
       [2, 21, 'J.P. Morgan Chase'],
       [4, 25, 'Wells Fargo'],
       [5, 27, 'Alphabet'],
       [6, 26, 'Bank of America Corp.'],
       [7, 28, 'Microsoft'],
       [8, 35, 'Johnson & Johnson'],
       [9, 30, 'Citigroup'],
       [10, 148, 'Altria Group'],
       [12, 92, 'Gilead Sciences'],
       [13, 14, 'Verizon'],
       [15, 20, 'Fannie Mae'],
       [16, 32, 'IBM'],
       [17, 60, 'Cisco Systems'],
       [18, 36, 'Procter & Gamble'],
       [19, 47, 'Intel'],
       [20, 98, 'Facebook'],
       [22, 52, 'Disney'],
       [23, 81, 'Oracle'],
       [25, 31, 'Comcast'],
       [28, 39, 'Freddie Mac'],
       [29, 123, 'Amgen'],
       [30, 78, 'Goldman Sachs Group'],
       [31, 310, 'eBay'],
       [32, 54, 'Pfizer'],
       [34, 104, 'Philip Morris International'],
       [35, 64, 'Coca-Cola'],
       [36, 44, 'PepsiCo'],
       [37, 223, 'Reynolds American'],
       [38, 187, 'Visa'],
       [39, 76, 'Morgan Stanley'],
       [40, 111, 'AbbVie

In [115]:
# Ques 97
revenue_order = np.argsort(revenue)[::-1]
revenue_rank = np.arange(1,len(revenue_order)+1)

companies = data[revenue_order, 1]

original_rank = data[revenue_order, 0]

difference_in_rank = np.abs(revenue_rank - original_rank)

compare = np.column_stack((revenue_rank, original_rank, companies))

data[revenue_order][difference_in_rank > 100]

array([], shape=(0, 10), dtype=object)

In [116]:
profit_order = np.argsort(profits)[::-1]
profit_rank = np.arange(1,len(profit_order)+1)
data[profit_order]


array([[3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [21, 'J.P. Morgan Chase', '2,43,355', ..., '1.2%', '$24,90,972',
        '$3,13,761'],
       [2, 'Berkshire Hathaway', '3,67,700', ..., '0.0%', '$6,20,854',
        '$4,11,035'],
       ...,
       [343, 'Chesapeake Energy', '3,300', ..., '-', '$13,028', '$5,394'],
       [173, 'Halliburton', '50,000', ..., '-', '$27,000', '$42,662'],
       [196, 'FirstEnergy', '15,707', ..., '-', '$43,148', '$14,118']],
      shape=(500, 10), dtype=object)

In [117]:
# Ques 98
revenue_order = np.argsort(revenue)[::-1]
revenue_rank = np.arange(1,len(revenue_order)+1)
revenue_rank_by_company = np.empty(len(revenue), dtype=int)
revenue_rank_by_company[revenue_order] = np.array(revenue_rank)

profit_order = np.argsort(profits)[::-1]
profit_rank = np.arange(1,len(profit_order)+1)
profit_rank_by_company = np.empty(len(revenue), dtype=int)
profit_rank_by_company[profit_order] = np.array(profit_rank)

assets_order = np.argsort(assets)[::-1]
assets_rank = np.arange(1,len(assets_order)+1)
assets_rank_by_company = np.empty(len(revenue), dtype=int)
assets_rank_by_company[assets_order] = np.array(assets_rank)

market_value_order = np.argsort(market_value)[::-1]
market_value_rank = np.arange(1,len(market_value_order)+1)
market_value_rank_by_company = np.empty(len(revenue), dtype=int)
market_value_rank_by_company[market_value_order] = np.array(market_value_rank)

sum_of_rank = revenue_rank_by_company + profit_rank_by_company + assets_rank_by_company + market_value_rank_by_company

index_to_compare = np.argsort(sum_of_rank)

data[index_to_compare][:5]

array([[2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [25, 'Wells Fargo', '2,69,100', 27.0, '$94,176', '4.6%',
        '$21,938.0', '-4.2%', '$19,30,115', '$2,78,516'],
       [26, 'Bank of America Corp.', '2,08,024', 26.0, '$93,662', '0.7%',
        '$17,906.0', '12.7%', '$21,87,702', '$2,36,182']], dtype=object)

In [118]:
# Ques 99
mean = np.nanmean(clean_data,axis=0)
median = np.nanmedian(clean_data, axis=0)
min_values = np.nanmin(clean_data, axis=0)
max_values = np.nanmax(clean_data, axis=0)
std = np.nanstd(clean_data, axis=0)

table_2 = np.vstack((mean, median, min_values, max_values, std))
table_2

array([[ 2.41117480e+04,  1.78347535e+03,  8.03893400e+04,
         4.13223979e+04],
       [ 1.13840000e+04,  6.87950000e+02,  1.93245000e+04,
         1.92055000e+04],
       [ 5.14500000e+03, -6.17700000e+03,  4.37000000e+02,
         1.20000000e+02],
       [ 4.85873000e+05,  4.56870000e+04,  3.28796800e+06,
         7.53718000e+05],
       [ 3.82989968e+04,  3.93260648e+03,  2.70155140e+05,
         7.32324719e+04]])

In [119]:
# Ques 100
count = np.count_nonzero(~np.isnan(clean_data), axis=0)
mean = np.nanmean(clean_data,axis=0)
std = np.nanstd(clean_data, axis=0)
min_values = np.nanmin(clean_data, axis=0)
_25_ = np.nanpercentile(clean_data, 25, axis=0)
_50_ = np.nanpercentile(clean_data, 50, axis=0)
_75_ = np.nanpercentile(clean_data, 75, axis=0)
max_values = np.nanmax(clean_data, axis=0)

table_3 = np.vstack((count, mean, std, min_values, _25_, _50_, _75_, max_values))
table_3

array([[ 5.00000000e+02,  5.00000000e+02,  5.00000000e+02,
         5.00000000e+02],
       [ 2.41117480e+04,  1.78347535e+03,  8.03893400e+04,
         4.13223979e+04],
       [ 3.82989968e+04,  3.93260648e+03,  2.70155140e+05,
         7.32324719e+04],
       [ 5.14500000e+03, -6.17700000e+03,  4.37000000e+02,
         1.20000000e+02],
       [ 7.24500000e+03,  2.39900000e+02,  8.43650000e+03,
         7.46500000e+03],
       [ 1.13840000e+04,  6.87950000e+02,  1.93245000e+04,
         1.92055000e+04],
       [ 2.26052500e+04,  1.78019384e+03,  4.81260000e+04,
         4.13223979e+04],
       [ 4.85873000e+05,  4.56870000e+04,  3.28796800e+06,
         7.53718000e+05]])

# Remaining Topics

Reshaping, Combining & Splitting

**Easy**

101. Take the first 100 rows of clean_data and reshape them into an array with 20 rows. Print the resulting shape.

102. Take the Revenue, Profit, and Assets columns from clean_data. Create a 1D array from them using both ravel() and flatten(). Print their shapes.

**Medium**

103. Find the top 10 companies by Revenue and the top 10 companies by Profit. Combine the two resulting company datasets vertically into a single NumPy array.

104. Create a NumPy array containing the following columns in this exact order:

    Rank
    Company Name
    Revenue
    Profit
    Assets
    Market Value

**Hard**

105. Split the complete data array into 5 equal parts and calculate the average Revenue for each part.

In [120]:
clean_data[:100].reshape(20,20)

array([[ 4.85873000e+05,  1.36430000e+04,  1.98825000e+05,
         2.18619000e+05,  2.23604000e+05,  2.40740000e+04,
         6.20854000e+05,  4.11035000e+05,  2.15639000e+05,
         4.56870000e+04,  3.21686000e+05,  7.53718000e+05,
         2.05004000e+05,  7.84000000e+03,  3.30314000e+05,
         3.40056000e+05,  1.92487000e+05,  2.25800000e+03,
         5.65630000e+04,  3.14390000e+04],
       [ 1.84840000e+05,  7.01700000e+03,  1.22810000e+05,
         1.57793000e+05,  1.77526000e+05,  5.31700000e+03,
         9.44620000e+04,  8.13100000e+04,  1.66380000e+05,
         9.42700000e+03,  2.21690000e+05,  5.29680000e+04,
         1.63786000e+05,  1.29760000e+04,  4.03821000e+05,
         2.55679000e+05,  1.51800000e+05,  4.59600000e+03,
         2.37951000e+05,  4.63490000e+04],
       [ 1.46850000e+05,  1.42790000e+03,  3.36560000e+04,
         1.92290000e+04,  1.35987000e+05,  2.37100000e+03,
         8.34020000e+04,  4.23031000e+05,  1.26661000e+05,
         8.83100000e+03,  3.6

In [121]:
clean_data[:,:3].flatten()

array([4.85873e+05, 1.36430e+04, 1.98825e+05, ..., 5.14500e+03,
       5.72000e+01, 2.28100e+03], shape=(1500,))

In [122]:
clean_data[:,:3].ravel()

array([4.85873e+05, 1.36430e+04, 1.98825e+05, ..., 5.14500e+03,
       5.72000e+01, 2.28100e+03], shape=(1500,))

In [123]:
np.vstack((data[revenue_order][:10],data[profit_order][:10]))

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004', '-16.7%',
        '$7,840.0', '-51.5%', '$3,30,314', '$3,40,056'],
       [5, 'McKesson', '68,000', 5.0, '$1,92,487', '6.2%', '$2,258.0',
        '53.0%', '$56,563', '$31,439'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
        '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
       [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526', '15.8%',
        '$5,317.0', '1.5%', '$94,462', '$81,310'],
       [8, 'General Motors', '2,25,000', 8.0, '$1,66,380', '9.2%',
        '$9,427.0', '-2.7%', '$2,21,690', '$52,968'],
       [9, 'AT&T', '2,68,540', 10.0, '$1,6

In [124]:
New_array_1 = np.column_stack((data[:,:2],clean_data))

In [125]:
splitted = np.array_split(New_array_1,5)

Part_1 = np.mean(splitted[0][:,2])
Part_2 = np.mean(splitted[1][:,2])
Part_3 = np.mean(splitted[2][:,2])
Part_4 = np.mean(splitted[3][:,2])
Part_5 = np.mean(splitted[4][:,2])